application:
  config:
    auth-url: http://localhost:8222/api/v1/auth
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day


eureka:
  client:
    register-with-eureka: false
  instance:
    hostname: localhost

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: exercises
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/exercises/**
        - id: exercise-plan
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/generate-workout/**
        - id: auth
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**
        - id: workout
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/workout/**
        - id: userExercise
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/userExercise/**
        - id: workoutDay
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/workoutDay/**

management:
  tracing:
    sampling:
      probability: 1.0
