application:
  config:
    exercises-url: http://localhost:8222/api/v1/exercises

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070

spring:
  application:
    name: openai-service

management:
  tracing:
    sampling:
      probability: 1.0
